force-app/main/default/objects/Car__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KPHB</fullName>
            </value>
            <value>
                <fullName>Madhapur</fullName>
            </value>
            <value>
                <fullName>LB Nagar</fullName>
            </value>
            <value>
                <fullName>Marthahalli</fullName>
            </value>
            <value>
                <fullName>BTM</fullName>
            </value>
            <value>
                <fullName>Hebbal</fullName>
            </value>
            <value>
                <fullName>Tambaram</fullName>
            </value>
            <value>
                <fullName>guindy</fullName>
            </value>
            <value>
                <fullName>Red hills</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/CarModel__c.field-meta.xml
<CustomField>
    <fullName>CarModel__c</fullName>
    <label>CarModel</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/CarNumber__c.field-meta.xml
<CustomField>
    <fullName>CarNumber__c</fullName>
    <label>CarNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/CarOwner__c.field-meta.xml
<CustomField>
    <fullName>CarOwner__c</fullName>
    <label>CarOwner</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/CarPrice__c.field-meta.xml
<CustomField>
    <fullName>CarPrice__c</fullName>
    <label>CarPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/OwnerNumber__c.field-meta.xml
<CustomField>
    <fullName>OwnerNumber__c</fullName>
    <label>OwnerNumber</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CarController.cls
public class CarController{

 //demo 1

public Car__c Car{get;set;}

public boolean flag {get;set;}

public String currentRecordId = null;

Public Static Id id;

public  Car__c getCar() {

      return Car;
}

public CarController(){

    Car= new  Car__c();  
    
   currentRecordId = ApexPages.CurrentPage().getparameters().get('id');
   if(currentRecordId !=null){
   flag =true;
   
Car = [select id, Name, CarModel__c, CarNumber__c, CarPrice__c, Email__c, CarOwner__c, OwnerNumber__c, Branch__c,

Area__c from Car__c where id =: currentRecordId ];
                                       } 
        else { 
        flag=false;
        
        
        }                               
  
}


 public pageReference doInsert() {
 
 
    System.debug('----- Car.CarModel__c---'+ Car.CarModel__c);
    
 if(Car.CarModel__c!= null && Car.CarModel__c!=''){
     Car.CarModel__c= Car.CarModel__c; 
 }
    
   if(Car.CarNumber__c != null && Car.CarNumber__c!=''){
  Car.CarNumber__c = Car.CarNumber__c;
 }
    
   
   if(Car.CarPrice__c!= null){
 Car.CarPrice__c = Car.CarPrice__c;

 }
 
    if(Car.Email__c!=null && Car.Email__c!=''){
 Car.Email__c = Car.Email__c;
 }
 
 
    if(Car.CarOwner__c!=null && Car.CarOwner__c!=''){
 Car.CarOwner__c = Car.CarOwner__c;
 }
    

   if(Car.OwnerNumber__c!=null && Car.OwnerNumber__c!=''){
 Car.OwnerNumber__c = Car.OwnerNumber__c;
 }
 
   if(Car.Branch__c!=null && Car.Branch__c!=''){
 Car.Branch__c = Car.Branch__c;
 }
 
  
  
  
   if(Car.Area__c!=null && Car.Area__c!=''){
 Car.Area__c = Car.Area__c;
 }
 
    System.debug(' -----  '+Car);
 // if(Car!=null) 
  
  Upsert Car;
 
    
  id = Car.id;
    PageReference pageRef = new PageReference('/apex/CarVfp?id='+id);
        pageRef.setRedirect(true);
        return pageRef;
}  

 

 public pageReference Edit() {
      
      ID id = ApexPages.CurrentPage().getparameters().get('id');
 
        PageReference pageRef = new PageReference('/apex/CarVfp?id='+id);
        pageRef.setRedirect(true);
        return pageRef;
    }  


        
             
public pageReference Cancel() {
        PageReference pageRef = new PageReference('/Home/home.jsp/');
        pageRef.setRedirect(true);
        return pageRef;
    }            

}