force-app/main/default/objects/Car__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Branch__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>KPHB</fullName>
            </value>
            <value>
                <fullName>Madhapur</fullName>
            </value>
            <value>
                <fullName>LB Nagar</fullName>
            </value>
            <value>
                <fullName>Marthahalli</fullName>
            </value>
            <value>
                <fullName>BTM</fullName>
            </value>
            <value>
                <fullName>Hebbal</fullName>
            </value>
            <value>
                <fullName>Tambaram</fullName>
            </value>
            <value>
                <fullName>guindy</fullName>
            </value>
            <value>
                <fullName>Red hills</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car__c/fields/CarPrice__c.field-meta.xml
<CustomField>
    <fullName>CarPrice__c</fullName>
    <label>CarPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DeleteController.cls
public with sharing class DeleteController{    
    public String CId{get;set;}
    
    List <Car__c> dlt = new List<Car__c>();  
      
    public List<Car__c> getCar() {
    
        dlt =[select id,Name,Branch__c,Area__c,CarPrice__c from Car__c];
        
        return dlt;
    }   
    
    Car__c CarDlt = new Car__c();    
    
    public PageReference DoDelete() {
    
        CarDlt=[select Id from Car__c where id =:CId];
        
        Delete CarDlt;
        
        pagereference ref=new pagereference('/apex/Mydelete');
        
        ref.setredirect(true);
        
        return ref;
    }
}